# Generated by Django 3.1.2 on 2020-12-01 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0005_shoppinglist_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='shares',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
