# Generated by Django 3.1.2 on 2021-01-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
